language : android

jdk : oraclejdk8

android:
  components:
  - platform-tools                # ADB
  - tools                         # 실제 안드로이드 SDK
  - build-tools-27                # 빌드툴
  - android-27                    # 타겟 버전
  - extra-android-m2repository    # 안드로이드 라이브러리

before_install:
  - chmod +x gradlew

script: ./gradlew build